/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Concept_note_overview: typeof import('./src/components/pages/admin/concept_note_overview.vue')['default']
    Concept_note_reviewing: typeof import('./src/components/pages/researcher/status/concept_note_reviewing.vue')['default']
    Concept_note_submissions: typeof import('./src/components/pages/admin/concept_note_submissions.vue')['default']
    Concept_note_tab: typeof import('./src/components/pages/researcher/tab/concept_note_tab.vue')['default']
    copy: typeof import('./src/components/pages/researcher/status/no_status copy.vue')['default']
    Create_research_project_modal: typeof import('./src/components/pages/researcher/modals/create_research_project_modal.vue')['default']
    Create_user_modal: typeof import('./src/components/pages/admin/create_user_modal.vue')['default']
    Initial_presentation: typeof import('./src/components/pages/researcher/tabs/initial_presentation.vue')['default']
    Initial_presentation_tab: typeof import('./src/components/pages/researcher/tab/initial_presentation_tab.vue')['default']
    Initial_presentation_tabs: typeof import('./src/components/pages/researcher/tabs/initial_presentation_tabs.vue')['default']
    Login: typeof import('./src/components/pages/Login.vue')['default']
    Nav_bar: typeof import('./src/components/nav_bar.vue')['default']
    No_status: typeof import('./src/components/pages/researcher/status/no_status.vue')['default']
    Panelist: typeof import('./src/components/pages/panelist/index.vue')['default']
    Research_table: typeof import('./src/components/pages/researcher/research_table.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Submit_concept_note: typeof import('./src/components/pages/researcher/submit_concept_note.vue')['default']
    Title_presentation_tab: typeof import('./src/components/pages/researcher/tab/title_presentation_tab.vue')['default']
    Title_presentation_waiting_for_response: typeof import('./src/components/pages/researcher/status/title_presentation_waiting_for_response.vue')['default']
    Title_presentation_waiting_response: typeof import('./src/components/pages/researcher/status/title_presentation_waiting_response.vue')['default']
    User_list: typeof import('./src/components/pages/admin/user_list.vue')['default']
    Ver: typeof import('./src/components/pages/researcher/status/ver.vue')['default']
  }
}
