/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Concept_note_overview: typeof import('./src/components/pages/admin/concept_note_overview.vue')['default']
    Concept_note_submissions: typeof import('./src/components/pages/admin/concept_note_submissions.vue')['default']
    Create_user: typeof import('./src/components/pages/admin/create_user.vue')['default']
    Create_user_modal: typeof import('./src/components/pages/admin/create_user_modal.vue')['default']
    Login: typeof import('./src/components/pages/Login.vue')['default']
    Nav_bar: typeof import('./src/components/nav_bar.vue')['default']
    Research_table: typeof import('./src/components/pages/researcher/research_table.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User_list: typeof import('./src/components/pages/admin/user_list.vue')['default']
  }
}
